import 'modelClass.dart';
import 'package:flutter/material.dart';

class cameraData {
  final List<productListModel> cameraList = [
    productListModel(
        1,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera.png"),
    productListModel(
        2,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera1.png"),
    productListModel(
        3,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera2.png"),
    productListModel(
        4,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera3.png"),
    productListModel(
        5,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera4.png"),
    productListModel(
        6,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera5.png"),
    productListModel(
        7,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera6.png"),
    productListModel(
        8,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera.png"),
    productListModel(
        9,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera3.png"),
    productListModel(
        3,
        "Camera",
        "Cameras are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/camera/camera2.png"),
  ];
}
