import 'modelClass.dart';
import 'package:flutter/material.dart';

class earPhoneData {
  final List<productListModel> earPhoneList = [
    productListModel(
        1,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone.png"),
    productListModel(
        2,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone1.png"),
    productListModel(
        3,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone2.png"),
    productListModel(
        4,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone3.png"),
    productListModel(
        5,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone4.png"),
    productListModel(
        6,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone5.png"),
    productListModel(
        7,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone6.png"),
    productListModel(
        8,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone7.png"),
    productListModel(
        9,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone4.png"),
    productListModel(
        5,
        "Earphone",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/earphone/earphone4.png"),
  ];
}
