import 'package:araianibazar/modelClass.dart';
import 'package:flutter/material.dart';

class gearData {
  final List<productListModel> gearList = [
    productListModel(
        1,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear.png"),
    productListModel(
        2,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear1.png"),
    productListModel(
        3,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear2.png"),
    productListModel(
        4,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear.png"),
    productListModel(
        5,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear2.png"),
    productListModel(
        6,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear1.png"),
    productListModel(
        7,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear2.png"),
    productListModel(
        8,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear.png"),
    productListModel(
        9,
        "Gear",
        "Gears are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/gear/gear1.png"),
  ];
}
