import 'modelClass.dart';
import 'package:flutter/material.dart';

class headPhoneData {
  final List<productListModel> headPhoneList = [
    productListModel(
        1,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-red.png"),
    productListModel(
        2,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-black.png"),
    productListModel(
        3,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-amber.png"),
    productListModel(
        4,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-blue.png"),
    productListModel(
        5,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-pink.png"),
    productListModel(
        6,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-white.png"),
    productListModel(
        7,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-blue2.png"),
    productListModel(
        8,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-red2.png"),
    productListModel(
        9,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-black3.png"),
    productListModel(
        7,
        "Headphone",
        "Headphones are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/headphone/headphone-blue2.png"),
  ];
}
