import 'package:araianibazar/modelClass.dart';
import 'package:flutter/material.dart';

class helmetData {
  final List<productListModel> helmetList = [
    productListModel(
        1,
        "Helmet",
        "Helmet are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet1.png"),
    productListModel(
        2,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet2.png"),
    productListModel(
        3,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet3.png"),
    productListModel(
        4,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet4.png"),
    productListModel(
        5,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet5.png"),
    productListModel(
        6,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet6.png"),
    productListModel(
        7,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet7.png"),
    productListModel(
        8,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet8.png"),
    productListModel(
        9,
        "Helmet",
        "Earphone are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/helmet/helmet9.png"),
  ];
}
