import 'modelClass.dart';
import 'package:flutter/material.dart';

class speakerData {
  final List<productListModel> speakerList = [
    productListModel(
        1,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker.png"),
    productListModel(
        2,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker1.png"),
    productListModel(
        3,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker5.png"),
    productListModel(
        4,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker3.png"),
    productListModel(
        5,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker4.png"),
    productListModel(
        6,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker5.png"),
    productListModel(
        7,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker.png"),
    productListModel(
        8,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker2.png"),
    productListModel(
        9,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker3.png"),
        productListModel(
        1,
        "Speaker",
        "Speaker are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/speaker/speaker.png"),
  ];
}
