import 'modelClass.dart';
import 'package:flutter/material.dart';

class vrsetData {
  final List<productListModel> vrsetList = [
    productListModel(
        1,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset5.png"),
    productListModel(
        2,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset6.png"),
    productListModel(
        3,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset2.png"),
    productListModel(
        4,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset3.png"),
    productListModel(
        5,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset4.png"),
    productListModel(
        6,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset5.png"),
    productListModel(
        7,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset1.png"),
    productListModel(
        8,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset2.png"),
    productListModel(
        9,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset.png"),
        productListModel(
        5,
        "Vr headset",
        "Vr headset are a pair of small loudspeaker drivers worn on or around the head over a user's ears. They are electroacoustic transducers, which convert an electrical signal to a corresponding sound. Headphones let a single user listen to an audio",
        10,
        2,
        20,
        200,
        4,
        "assets/images/VRset/vrheadset4.png"),
  ];
}
